# .github/workflows/ci.yml
name: ci
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  test-and-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: npm ci || npm i
      - run: npm test
      - name: Build preview zip
        run: zip -r snipguard-preview.zip . -x "*.git*"
      - uses: actions/upload-artifact@v4
        with:
          name: snipguard-preview
          path: snipguard-preview.zip
